require('dotenv').config()
const express = require('express')
const path = require('path')
const app = express()
const {User,Log} = require('./models')
app.use(express.static(path.join(__dirname, 'public')))
app.use(express.urlencoded({ extended: true }))
app.use(express.json())

app.use(require('./routes'))
require('./config').sync()
.then(()=> app.listen(process.env.PORT || 3000))
.catch((e)=> console.log(e))